name: Auto-Update docs.json

# Trigger on pushes that affect the assets folder
on:
  push:
    branches: [ main, master ]
    paths:
      - 'electricalop/assets/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'electricalop/assets/**'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Navigate to project directory
      run: cd electricalop

    - name: Make generate-docs.js executable
      run: chmod +x electricalop/generate-docs.js

    - name: Run docs generator script
      run: |
        cd electricalop
        node generate-docs.js

    - name: Check if docs.json changed
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add electricalop/data/docs.json
        git commit -m "Auto-update docs.json - $(date)"
        git push
